### ISSUE TITLE
Can't build with Intellij.

### ISSUE THREAD

**Issue by EmileSonneveld** [THM-MoTE/MoVE#5]
I get different kind of errors. The one I get on first opening is:
`(update) sbt.librarymanagement.ResolveException: unresolved dependency: com.eed3si9n#sbt-assembly;0.14.3: not found`
I got one step further commented out `addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.3")` in plugin.sbt, but then bounced on an infinite wall of errors.

I also tried:
- Changing sbt version
- Changing between java 1.8 and java 11
- Change scalaVersion in build.sbt from 2.11.8 to 2.12.8

What should I do to get this project building again? I would like to test my static analysis tool on it.

**Comment by njustus** [comment]
Hi Emile,

thanks for the issue. Because of all the changes introduced in java 9, 10 and 11 it's not possible to build the project using jdk >= 8, so first: you do need jdk8.

Because we depend on JavaFX and the `jfxrt.jar` isn't in the default classpath of sbt, we add it manually to it in the [build file](https://github.com/THM-MoTE/MoVE/blob/8acc98a5ade6d117a79bcccb0e35e7a6ef5b8af1/build.sbt#L6). This step requires that `$JAVA_HOME` is set and points to a jdk8 installation. Start sbt using:
```sh
JAVA_HOME=<path to jdk8> sbt
JAVA_HOME='/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home' sbt
```
At least for me it's than possible to build the project by running `;compile;run` in sbt console.
I can't help you in IntelliJ because i don't use it, but if you set the `$JAVA_HOME` variable you should be able to just import the project from sbt.

Please try to build the dev branch, there i fixed the `sbt-assembly` resolution error ;).

**Comment by EmileSonneveld** [comment]
Hi Nico, 

Thank you! That indeed solved my problem.

I also had a problem with the 'THM-MoTE/recently' dependency, so I temporary disabled that one.

Btw, the results of my static analysis:
- No methods found with Cyclomatic Complexity>20
- 3 potential 'God classes' found: SvgCodeGenerator, ModelicaCodeGenerator, MoveCtrl, 
- Type hierarchy without isolated types looks as follows: [types_withoud_isolated_nodes_MoVE.pdf](https://github.com/THM-MoTE/MoVE/files/3098242/types_withoud_isolated_nodes_MoVE.pdf)
- The LOCs and number of methods grew very steadily over time:
![graph_move](https://user-images.githubusercontent.com/2298426/56426146-756b1500-62b7-11e9-8abf-93da4218ddb8.PNG)
